export enum ErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  PEPTIDE_NOT_FOUND = 'PEPTIDE_NOT_FOUND',

  INVALID_BODY_PROVIDED = 'INVALID_BODY_PROVIDED',
  INVALID_QUERY_PROVIDED = 'INVALID_QUERY_PROVIDED'
}
